version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.144.0
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"

  strands-agent:
    build: .
    container_name: strands-agent
    depends_on:
      - otel-collector
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "strands-agent"
      SPLUNK_REALM: us1
      SPLUNK_ACCESS_TOKEN: 6Fmh2CKA_RYqrMTT1I2E0A
