version: "3.9"

services:
  otel-collector:
    image: public.ecr.aws/splunk/otelcol:0.144.0
    container_name: otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    restart: unless-stopped

  strands-agent:
    build:
      context: .
    container_name: strands-agent
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: "strands-agent"
    depends_on:
      - otel-collector
    tty: true
